name: bergamot-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cmake=3.21.1
  - mkl=2021.3.0
  - git=2.32.0
  - pip:
    - sacrebleu=1.5.1
    - mtdata=0.2.9
    - fasttext=0.9.2
    - tensorboard=2.5.0
    - tensorboardX=2.2
    - click=8.0.1