cluster: "submit.py"
cluster-status: "status.py"
jobscript: "jobscript.sh"
jobs: 10
restart-times: 0
immediate-submit: false
verbose: false
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
rerun-incomplete: true  # recomended for cluster submissions
keep-going: false
default-resources: "mem_mb=5980"