# https://github.com/marian-nmt/marian-examples/tree/master/transformer
# https://github.com/marian-nmt/marian-examples/tree/master/wmt2017-uedin
dim-vocabs: [32000, 32000]
type: transformer
task: transformer-big