####
# Test config, it rus the pipeline quickly end to end
###


root: ""
cuda: ""
deps: false
gpus: ""
workspace: ""

experiment:
  name: test
  src: ru
  trg: en

  teacher-ensemble: 2
  backward-model: ""

  mono-max-sentences-src: 100000
  mono-max-sentences-trg: 200000
  split-length: 100000

  best-model: chrf

  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      mtdata_neulab_tedtalksv1_train: 0.6

training:
  backward:
    after: 1000u
  teacher-all:
    after: 2000u
  teacher-parallel:
    after: 1000u
  student:
    after: 1000u
  student-finetune:
    after: 1000u


datasets:
  train:
    - opus_ada83/v1
    - opus_GNOME/v1
    - mtdata_neulab_tedtalksv1_train
  devtest:
    - flores_dev
    - mtdata_newstest2019_ruen
  test:
    - flores_devtest
    - sacrebleu_wmt20
    - sacrebleu_wmt18
  mono-src:
    - news-crawl_news.2020
  mono-trg:
    - news-crawl_news.2020


