####
# Example of a production config
# Change language pair, experiment name, datasets and other settings if needed
# Training low resource languages might require more tuning of pipeline/training/configs
###


# These settings depend on execution environment
# They are set in the Makefile
root: ""
cuda: ""
deps: false
gpus: ""
numgpus: ""
workspace: ""
mariancmake: ""


experiment:
  name: prod
  src: ru
  trg: en

  teacher-ensemble: 4
  # path to a pretrained backward model (optional)
  backward-model: ""

  # limits per downloaded dataset
  mono-max-sentences-src: 100000000
  mono-max-sentences-trg: 20000000
  # split corpus to parallelize translation
  split-length: 2000000
  # vocab training sample
  spm-sample-size: 10000000

  best-model: chrf

  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      opus_CCAligned/v1: 0.7
      opus_WikiMatrix/v1: 0.7
      opus_OpenSubtitles/v2018: 0.9
      opus_bible-uedin/v1: 0.7
      mtdata_cc_aligned: 0.7
      mtdata_wiki_titles_v1: 0.7
      mtdata_WikiMatrix_v1: 0.7
      mtdata_wiki_titles_v2: 0.7
      mtdata_wmt13_commoncrawl: 0.7
      # 0 = skip filtering
      opus_ParaCrawl/v8: 0


marian-args:
# these configs override pipeline/train/configs
  training-backward:
    # change based on available training data
    after: 10e
  training-teacher-all:
    # remove for low resource languages or if training without augmentation
    after: 2e
# these configs override pipeline/translate/decoder.yml
  decoding-backward:
    # 12 Gb GPU, s2s model
    mini-batch-words: 2000
    # 2080ti or newer
    precision: float16
  decoding-teacher:
    # 12 Gb GPU, ensemble of 4 teachers
    mini-batch-words: 500
    # 2080ti or newer
    precision: float16


datasets:
  # parallel training corpus
  train:
    - opus_ada83/v1
    - opus_UN/v20090831
    - opus_GNOME/v1
    - opus_wikimedia/v20210402
    - opus_CCMatrix/v1
    - opus_Wikipedia/v1.0
    - opus_tico-19/v2020-10-28
    - opus_KDE4/v2
    - opus_OpenSubtitles/v2018
    - opus_MultiUN/v1
    - opus_GlobalVoices/v2018q4
    - opus_ELRC_2922/v1
    - opus_PHP/v1
    - opus_Tatoeba/v2021-03-10
    - opus_Tanzil/v1
    - opus_XLEnt/v1.1
    - opus_TildeMODEL/v2018
    - opus_Ubuntu/v14.10
    - opus_TED2013/v1.1
    - opus_infopankki/v1
    - opus_EUbookshop/v2
    - opus_ParaCrawl/v8
    - opus_Books/v1
    - opus_bible-uedin/v1
    - opus_WikiMatrix/v1
    - opus_QED/v2.0a
    - opus_CCAligned/v1
    - opus_TED2020/v1
    - opus_News-Commentary/v16
    - opus_UNPC/v1.0
    - mtdata_cc_aligned
    - mtdata_airbaltic
    - mtdata_neulab_tedtalksv1_train
    - mtdata_neulab_tedtalksv1_dev
    - mtdata_wmt13_commoncrawl
    - mtdata_czechtourism
    - mtdata_paracrawl_bonus
    - mtdata_worldbank
    - mtdata_wiki_titles_v1
    - mtdata_WikiMatrix_v1
    - mtdata_wmt18_news_commentary_v13
    - mtdata_wiki_titles_v2
    - mtdata_news_commentary_v14
    - mtdata_neulab_tedtalksv1_test
    - mtdata_JW300
  # datasets to merge for validation while training
  devtest:
    - flores_dev
    - mtdata_newstest2019_ruen
    - mtdata_newstest2017_ruen
    - mtdata_newstest2015_ruen
    - mtdata_newstest2014_ruen
  # datasets for evaluation
  test:
    - flores_devtest
    - sacrebleu_wmt20
    - sacrebleu_wmt18
    - sacrebleu_wmt16
    - sacrebleu_wmt13
  # monolingual datasets (ex. paracrawl-mono_paracrawl8, commoncrawl_wmt16, news-crawl_news.2020)
  # to be translated by the teacher model
  mono-src:
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
    - news-crawl_news.2017
    - news-crawl_news.2016
    - news-crawl_news.2015
    - news-crawl_news.2014
    - news-crawl_news.2013
    - news-crawl_news.2012
    - news-crawl_news.2011
  # to be translated by the backward model to augment teacher corpus with back-translations
  # leave empty to skip augmentation step (high resource languages)
  mono-trg:
    - news-crawl_news.2020
    - news-crawl_news.2019
    - news-crawl_news.2018
    - news-crawl_news.2017
    - news-crawl_news.2016
    - news-crawl_news.2015


